spring:
  application:
    name: mcp-forwarder
  main:
    banner-mode: "console"
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /sse
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

logging:
  level:
    root: INFO
    com.example.mcp: DEBUG

downstream:
  base-url: "http://localhost:9000" # 请替换为真实下游服务地址
  path: "/query"
  api-key: "${DOWNSTREAM_API_KEY:}"
  api-key-header: "Authorization"
